app:
  yaUrl: "https://translate.api.cloud.yandex.net/translate/v2/translate"

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false



server:
  port: 7070

logging:
  config: classpath:log4j2-plain.xml



